name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: Luka-92/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MiApp-Android
          path: bin/*.apk
